name: Build app

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test

    - name: Build
      run: dotnet build --configuration Release PlaywrightAutomationFramework.csproj

    - name: Create the package
      run: dotnet pack --configuration Release PlaywrightAutomationFramework.csproj
      
    - name: Publish the package to GPR
      run: dotnet nuget push PlaywrightAutomationFramework/bin/Release/*.nupkg
